# Generated by Django 4.2.6 on 2023-10-17 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('r_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='id',
        ),
        migrations.AlterField(
            model_name='education',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='r_app.student'),
        ),
        migrations.AlterField(
            model_name='education',
            name='year',
            field=models.IntegerField(),
        ),
    ]
